# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbb5a66ed462cf1d765f8bbd9680398be911a715178ca7393d00f08dbdd8d11cd2f6da0608306787af96a74479f18c112416c612060bdfdf8577e393c7d017c

test:
  secret_key_base: a73edf71bf6b182ae93b1338d2d30ef00d18545b6962926f369f83e3de7f81194b8c4d42cda093eed8b9314c0ba177dc11691b937a06e09d8a22d76fca0f69fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
